# Work git configuration: conditionally override user.email for corporate
# remotes without putting internal hostnames or emails in tracked files.
# Called from ~/.localrc.secrets after secret variables are defined.
_git_configure_work_hosts() {
  local email="$1"; shift
  [[ -n "$email" && $# -gt 0 ]] || return 0

  local user_file="$HOME/.gitconfig.work.user"
  local work_file="$HOME/.gitconfig.work"
  local want_user want_work host

  want_user="[user]
	email = $email"

  want_work="# Generated by git/config.work.zsh — do not edit by hand"
  for host in "$@"; do
    want_work+="
[includeIf \"hasconfig:remote.*.url:https://${host}/**\"]
	path = ~/.gitconfig.work.user
[includeIf \"hasconfig:remote.*.url:sso://${host}/**\"]
	path = ~/.gitconfig.work.user
[includeIf \"hasconfig:remote.*.url:ssh://git@${host}/**\"]
	path = ~/.gitconfig.work.user
[includeIf \"hasconfig:remote.*.url:git@${host}:*\"]
	path = ~/.gitconfig.work.user
[includeIf \"hasconfig:remote.*.url:git@${host}:*/**\"]
	path = ~/.gitconfig.work.user"
  done

  if [[ ! -f "$user_file" || "$(<"$user_file")" != "$want_user" ]]; then
    (umask 077 && printf '%s\n' "$want_user" > "$user_file") 2>/dev/null
  fi
  if [[ ! -f "$work_file" || "$(<"$work_file")" != "$want_work" ]]; then
    (umask 077 && printf '%s\n' "$want_work" > "$work_file") 2>/dev/null
  fi
}
